import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "@/app/_components/Header";
import { Yusei_Magic } from "next/font/google";

const yusei = Yusei_Magic({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "カフェ：こもれび",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
    apple: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={yusei.className}>
        <main className="main text-center">
          <Header />
          <div className="news">{children}</div>
        </main>
      </body>
    </html>
  );
}
